name: Deploy Staging

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@v4
      - run: docker build -t pranidoctor-web:staging -f Dockerfile .
